### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by abergmeier** [devongovett/glsl.js#1]
Is this project striving to do a 1:1 translation or patch up OpenGL ES 2.0 variant?

**Comment by devongovett** [comment]
The goal is to implement the GLSL ES language for browsers that don't support WebGL, or devices whose GPUs are blacklisted for security reasons or just buggy cards.  I'm not exactly sure what you're asking, so let me know if I haven't answered your question.

**Comment by abergmeier** [comment]
That does answer my question.
I am curious though, for which scenarios you would use it, since GPU shaders are probably way fast than asm.js.

**Comment by devongovett** [comment]
Yep, like I said, browsers that don't support WebGL (lots of mobile devices, old IEs, Safari not enabled by default, etc), and browsers that support WebGL but where the GPUs are blacklisted (lots of those too, basically anything before 2009, and lots of current ones too).
